id: PYSEC-0000-CVE-2018-17581
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
details: CiffDirectory::readDirectory() at crwimage_int.cpp in Exiv2 0.26 has excessive
  stack consumption due to a recursive function, leading to Denial of service.
affected:
- package:
    name: exiv2
    ecosystem: PyPI
    purl: pkg:pypi/exiv2
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
references:
- type: EVIDENCE
  url: https://github.com/SegfaultMasters/covering360/blob/master/Exiv2
- type: FIX
  url: https://github.com/SegfaultMasters/covering360/blob/master/Exiv2
- type: WEB
  url: https://github.com/SegfaultMasters/covering360/blob/master/Exiv2
- type: EVIDENCE
  url: https://github.com/Exiv2/exiv2/issues/460
- type: FIX
  url: https://github.com/Exiv2/exiv2/issues/460
- type: REPORT
  url: https://github.com/Exiv2/exiv2/issues/460
- type: WEB
  url: https://usn.ubuntu.com/3852-1/
- type: ARTICLE
  url: https://lists.debian.org/debian-lts-announce/2019/02/msg00038.html
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2019/02/msg00038.html
- type: ADVISORY
  url: https://access.redhat.com/errata/RHSA-2019:2101
- type: ARTICLE
  url: https://lists.debian.org/debian-lts-announce/2023/01/msg00004.html
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2023/01/msg00004.html
aliases:
- CVE-2018-17581
modified: "2023-01-13T16:34:00Z"
published: "2018-09-28T09:29:00Z"
