id: PYSEC-0000-CVE-2019-17402
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
details: Exiv2 0.27.2 allows attackers to trigger a crash in Exiv2::getULong in types.cpp
  when called from Exiv2::Internal::CiffDirectory::readDirectory in crwimage_int.cpp,
  because there is no validation of the relationship of the total size to the offset
  and size.
affected:
- package:
    name: exiv2
    ecosystem: PyPI
    purl: pkg:pypi/exiv2
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
references:
- type: REPORT
  url: https://github.com/Exiv2/exiv2/issues/1019
- type: WEB
  url: https://usn.ubuntu.com/4159-1/
- type: ARTICLE
  url: https://lists.debian.org/debian-lts-announce/2019/12/msg00001.html
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2019/12/msg00001.html
- type: ARTICLE
  url: https://lists.debian.org/debian-lts-announce/2023/01/msg00004.html
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2023/01/msg00004.html
aliases:
- CVE-2019-17402
modified: "2023-01-13T16:19:00Z"
published: "2019-10-09T19:15:00Z"
