id: PYSEC-0000-CVE-2017-11591
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
details: There is a Floating point exception in the Exiv2::ValueType function in Exiv2
  0.26 that will lead to a remote denial of service attack via crafted input.
affected:
- package:
    name: exiv2
    ecosystem: PyPI
    purl: pkg:pypi/exiv2
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
references:
- type: EVIDENCE
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1473888
- type: REPORT
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1473888
- type: WEB
  url: https://usn.ubuntu.com/3852-1/
- type: ARTICLE
  url: https://lists.debian.org/debian-lts-announce/2023/01/msg00004.html
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2023/01/msg00004.html
aliases:
- CVE-2017-11591
modified: "2023-01-13T16:45:00Z"
published: "2017-07-24T01:29:00Z"
