affected:
- package:
    ecosystem: PyPI
    name: exiv2
    purl: pkg:pypi/exiv2
  ranges:
  - events:
    - introduced: '0'
    type: ECOSYSTEM
  versions:
  - '0.1'
  - 0.11.0
  - 0.11.1
  - 0.11.2
  - 0.11.3
  - 0.12.0
  - 0.12.1
  - 0.13.0
  - 0.13.1
  - 0.13.2
  - 0.14.0
  - 0.14.1
  - 0.15.0
  - 0.16.0
  - 0.16.1
  - 0.16.2
  - 0.16.2.post1
  - 0.16.3
  - 0.16.3.post1
  - 0.17.0
  - 0.17.1
  - '0.2'
  - '0.3'
  - 0.3.1
aliases:
- CVE-2018-10999
details: An issue was discovered in Exiv2 0.26. The Exiv2::Internal::PngChunk::parseTXTChunk
  function has a heap-based buffer over-read.
id: PYSEC-2018-128
modified: '2024-11-21T14:22:48.18647Z'
published: '2018-05-12T04:29:00Z'
references:
- type: EVIDENCE
  url: https://github.com/Exiv2/exiv2/issues/306
- type: REPORT
  url: https://github.com/Exiv2/exiv2/issues/306
- type: ARTICLE
  url: https://lists.debian.org/debian-lts-announce/2018/06/msg00010.html
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2018/06/msg00010.html
- type: ADVISORY
  url: https://www.debian.org/security/2018/dsa-4238
- type: WEB
  url: https://usn.ubuntu.com/3700-1/
- type: ARTICLE
  url: https://lists.debian.org/debian-lts-announce/2018/10/msg00012.html
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2018/10/msg00012.html
- type: ADVISORY
  url: https://security.gentoo.org/glsa/201811-14
severity:
- score: CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
  type: CVSS_V3
withdrawn: '2024-11-22T04:37:04Z'
