affected:
- package:
    ecosystem: PyPI
    name: pyboolector
    purl: pkg:pypi/pyboolector
  ranges:
  - events:
    - introduced: '0'
    - fixed: 3.1.0
    type: ECOSYSTEM
  versions:
  - 3.0.0.1
  - 3.0.0.20191102.28
  - 3.0.0.20191119.1
  - 3.0.0.20191119.2
aliases:
- CVE-2019-7560
- GHSA-g58x-799h-v9h6
details: In parser/btorsmt2.c in Boolector 3.0.0, opening a specially crafted input
  file leads to a use after free in get_failed_assumptions or btor_delete.
id: PYSEC-2019-252
modified: '2024-11-25T18:35:18.357593Z'
published: '2019-02-07T07:29:00Z'
references:
- type: EVIDENCE
  url: https://github.com/Boolector/boolector/issues/29
- type: FIX
  url: https://github.com/Boolector/boolector/issues/29
- type: REPORT
  url: https://github.com/Boolector/boolector/issues/29
- type: EVIDENCE
  url: https://github.com/Boolector/boolector/issues/28
- type: FIX
  url: https://github.com/Boolector/boolector/issues/28
- type: REPORT
  url: https://github.com/Boolector/boolector/issues/28
severity:
- score: CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
  type: CVSS_V3
