id: PYSEC-0000-CVE-2016-7151
severity:
- type: CVSS_V3
  score: CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
details: Capstone 3.0.4 has an out-of-bounds vulnerability (SEGV caused by a read
  memory access) in X86_insn_reg_intel in arch/X86/X86Mapping.c.
affected:
- package:
    name: capstone
    ecosystem: PyPI
    purl: pkg:pypi/capstone
  ranges:
  - type: GIT
    repo: https://github.com/capstone-engine/capstone
    events:
    - introduced: "0"
    - fixed: 87a25bb543c8e4c09b48d4b4a6c7db31ce58df06
  - type: ECOSYSTEM
    events:
    - introduced: "0"
references:
- type: EVIDENCE
  url: https://github.com/aquynh/capstone/pull/725
- type: WEB
  url: https://github.com/aquynh/capstone/pull/725
- type: FIX
  url: https://github.com/aquynh/capstone/commit/87a25bb543c8e4c09b48d4b4a6c7db31ce58df06
aliases:
- CVE-2016-7151
modified: "2019-05-16T14:04:00Z"
published: "2019-05-15T14:29:00Z"
