id: PYSEC-0000-CVE-2011-3587
details: Unspecified vulnerability in Zope 2.12.x and 2.13.x, as used in Plone 4.0.x
  through 4.0.9, 4.1, and 4.2 through 4.2a2, allows remote attackers to execute arbitrary
  commands via vectors related to the p_ class in OFS/misc_.py and the use of Python
  modules.
affected:
- package:
    name: products-plonehotfix20110928
    ecosystem: PyPI
    purl: pkg:pypi/products-plonehotfix20110928
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
references:
- type: FIX
  url: https://bugzilla.redhat.com/show_bug.cgi?id=742297
- type: FIX
  url: http://zope2.zope.org/news/security-vulnerability-announcement-cve-2011-3587
- type: FIX
  url: http://plone.org/products/plone-hotfix/releases/20110928/PloneHotfix20110928-1.0.zip
- type: FIX
  url: http://pypi.python.org/pypi/Products.PloneHotfix20110928/1.0
- type: FIX
  url: http://plone.org/products/plone/security/advisories/20110928
- type: ADVISORY
  url: http://plone.org/products/plone/security/advisories/20110928
- type: ADVISORY
  url: http://secunia.com/advisories/46221
- type: FIX
  url: http://plone.org/products/plone-hotfix/releases/20110928
- type: ADVISORY
  url: http://secunia.com/advisories/46323
aliases:
- CVE-2011-3587
modified: "2011-10-21T02:56:00Z"
published: "2011-10-10T10:55:00Z"
