id: PYSEC-0000-CVE-2010-3198
details: ZServer in Zope 2.10.x before 2.10.12 and 2.11.x before 2.11.7 allows remote
  attackers to cause a denial of service (crash of worker threads) via vectors that
  trigger uncaught exceptions.
affected:
- package:
    name: zope
    ecosystem: PyPI
    purl: pkg:pypi/zope
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
references:
- type: FIX
  url: https://mail.zope.org/pipermail/zope-announce/2010-September/002247.html
- type: ADVISORY
  url: https://mail.zope.org/pipermail/zope-announce/2010-September/002247.html
- type: WEB
  url: http://www.zope.org/Products/Zope/2.10.12/CHANGES.txt
- type: ADVISORY
  url: http://www.vupen.com/english/advisories/2010/2275
- type: WEB
  url: http://www.securityfocus.com/bid/42939
- type: WEB
  url: http://www.zope.org/Products/Zope/2.11.7/CHANGES.txt
- type: EVIDENCE
  url: https://bugs.launchpad.net/zope2/+bug/627988
- type: FIX
  url: https://bugs.launchpad.net/zope2/+bug/627988
- type: ADVISORY
  url: https://bugs.launchpad.net/zope2/+bug/627988
aliases:
- CVE-2010-3198
modified: "2010-09-10T04:00:00Z"
published: "2010-09-08T20:00:00Z"
