affected:
- package:
    ecosystem: PyPI
    name: Zope
  ranges:
  - events:
    - introduced: 2.10.0
    - fixed: 2.10.12
    type: ECOSYSTEM
- package:
    ecosystem: PyPI
    name: Zope
  ranges:
  - events:
    - introduced: 2.11.0
    - fixed: 2.11.7
    type: ECOSYSTEM
aliases:
- CVE-2010-3198
details: ZServer in Zope 2.10.x before 2.10.12 and 2.11.x before 2.11.7 allows remote
  attackers to cause a denial of service (crash of worker threads) via vectors that
  trigger uncaught exceptions.
id: PYSEC-2010-32
modified: '2024-11-25T18:35:18.357593Z'
published: '2010-09-08T20:00:00Z'
references:
- type: FIX
  url: https://mail.zope.org/pipermail/zope-announce/2010-September/002247.html
- type: ADVISORY
  url: https://mail.zope.org/pipermail/zope-announce/2010-September/002247.html
- type: WEB
  url: http://www.zope.org/Products/Zope/2.10.12/CHANGES.txt
- type: ADVISORY
  url: http://www.vupen.com/english/advisories/2010/2275
- type: WEB
  url: http://www.securityfocus.com/bid/42939
- type: WEB
  url: http://www.zope.org/Products/Zope/2.11.7/CHANGES.txt
- type: EVIDENCE
  url: https://bugs.launchpad.net/zope2/+bug/627988
- type: FIX
  url: https://bugs.launchpad.net/zope2/+bug/627988
- type: ADVISORY
  url: https://bugs.launchpad.net/zope2/+bug/627988
